---
- name: download rpm
  become: yes
  become_user: root
  command: 'wget --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" {{java_oracle_url}} -O /tmp/{{java_oracle_rpm}}'
  args:
    creates: /tmp/{{java_oracle_rpm}}

- name: install rpm
  become: yes
  become_user: root
  package: name=/tmp/{{java_oracle_rpm}} state=present
