---
- name: (RedHat) install java...
  package: name={{item}} state=present
  with_items:
    - java-1.{{java_ver}}.{{java_minor_ver}}-openjdk
    - java-1.{{java_ver}}.{{java_minor_ver}}-openjdk-devel
    - java-1.{{java_ver}}.{{java_minor_ver}}-openjdk-javadoc
  
